---
# Service to expose node app
apiVersion: v1
kind: Service
metadata:
    labels:
        name: webfrontend
    name: webfrontend
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
        app: node-app
